# Generated by Django 3.1.2 on 2021-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Auth_Db',
            fields=[
                ('Register_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Master_Db',
            fields=[
                ('Register_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Room_No', models.CharField(max_length=10)),
                ('Mobile_No', models.CharField(max_length=12)),
                ('Parent_No', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=10)),
                ('Class', models.CharField(max_length=10)),
                ('Father_Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Date_of_birth', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Today_Attendance_Db',
            fields=[
                ('Register_No', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Auth_Status', models.BooleanField()),
                ('Auth_Time', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=10)),
            ],
        ),
    ]
