# ACTIVATE TESTMODE TO BYPASS APIKEY AND OTP CHANGE
TEST_MODE = True

# SET AUTHENTICATION START AND END TIME IN 24HR INTEGER 
AUTH_ALLOW_START = 19
AUTH_ALLOW_END = 22

# RESET TODAY ATTENDANCE DB AND GENERATE REPORT - TIME IN 0-23 INT
RST_DB_GEN_RPRT_TIME = 0
